In [1]:
import pandas as pd
import numpy as np

from os import listdir

In [2]:
path = '../data/state_data_merged/'

In [3]:
listdir(path)

['MN.csv',
 'AZ.csv',
 'WA.csv',
 'WV.csv',
 'AL.csv',
 'NC.csv',
 'MO.csv',
 'NV.csv',
 'OR.csv',
 'TX.csv',
 'TN.csv',
 'ND.csv',
 'AK.csv',
 'CT.csv',
 '.DS_Store',
 'VT.csv',
 'MI.csv',
 'NE.csv',
 'VA.csv',
 'CA.csv',
 'DC.csv',
 'ID.csv',
 'KY.csv',
 'FL.csv',
 'PA.csv',
 'RI.csv',
 'DE.csv',
 'IA.csv',
 'KS.csv',
 'IL.csv',
 'SC.csv',
 'HI.csv',
 'IN.csv',
 'GA.csv',
 'SD.csv',
 '.ipynb_checkpoints',
 'WI.csv',
 'AR.csv',
 'NJ.csv',
 'NH.csv',
 'MS.csv',
 'MD.csv',
 'CO.csv',
 'UT.csv',
 'ME.csv',
 'LA.csv',
 'MA.csv',
 'NM.csv',
 'WY.csv',
 'OH.csv',
 'NY.csv',
 'OK.csv']

In [4]:
states_csv = [file for file in listdir(path) if '.csv' in file]

In [5]:
states_df = [pd.read_csv(path + file) for file in states_csv]

In [6]:
full_df = pd.concat(states_df)

In [7]:
full_df

,LEAID,CENSUSID,FIPST,CONUM,CSA,CBSA,NAME,STNAME,STABBR,SCHLEV,...,FL_W61,FL_V95,FL_V02,FL_K14,FL_CE1,FL_CE2,FL_CE3,District Name,Total,Graduation Rate
0,2700001,24506901700000,27,27137,N,20260,MOUNTAIN IRON-BUHL,Minnesota,MN,3,...,R,R,R,R,M,M,M,MOUNTAIN IRON-BUHL,31.0,0.9355
1,2700005,24502200900000,27,27043,N,N,UNITED SOUTH CENTRAL,Minnesota,MN,3,...,R,R,R,R,M,M,M,UNITED SOUTH CENTRAL,42.0,0.8810
2,2700006,24500720200000,27,27013,359,31860,MAPLE RIVER,Minnesota,MN,3,...,R,R,R,R,M,M,M,MAPLE RIVER,79.0,0.9747
3,2700007,24502320200000,27,27045,462,40340,KINGSLAND,Minnesota,MN,3,...,R,R,R,R,M,M,M,KINGSLAND,31.0,0.9677
4,2700008,24506920200000,27,27137,N,20260,ST LOUIS COUNTY,Minnesota,MN,3,...,R,R,R,R,M,M,M,ST LOUIS COUNTY,122.0,0.8607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,4033390,37507001200000,40,40139,N,25100,YARBROUGH,Oklahoma,OK,3,...,R,R,R,R,R,R,M,YARBROUGH,NaN,1.0000
426,4033480,37500902100000,40,40017,416,36420,YUKON,Oklahoma,OK,3,...,R,R,R,R,R,R,M,YUKON,NaN,0.9200
427,4033601,37500700800000,40,40013,206,20460,ROCK CREEK,Oklahoma,OK,3,...,R,R,R,R,R,R,M,ROCK CREEK,NaN,0.9000
428,4033602,37500801500000,40,40015,N,N,FORT COBB-BROXTON,Oklahoma,OK,3,...,R,R,R,R,R,R,M,FORT COBB-BROXTON,NaN,0.8000
429,4033603,37500800500000,40,40015,N,N,BINGER-ONEY,Oklahoma,OK,3,...,R,R,R,R,R,R,M,BINGER-ONEY,NaN,0.8000

In [8]:
full_df.to_csv('../data/' + str(len(states_df)) + '_states_merged.csv', index=False)